BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE service_orders CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE services CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE staff CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE billing CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE rooms CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE room_seq';
    EXECUTE IMMEDIATE 'DROP SEQUENCE customer_seq';
    EXECUTE IMMEDIATE 'DROP SEQUENCE billing_seq';
    EXECUTE IMMEDIATE 'DROP SEQUENCE staff_seq';
    EXECUTE IMMEDIATE 'DROP SEQUENCE service_seq';
    EXECUTE IMMEDIATE 'DROP SEQUENCE order_seq';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/