CREATE SEQUENCE room_seq START WITH 1;
CREATE SEQUENCE customer_seq START WITH 1;
CREATE SEQUENCE billing_seq START WITH 1;
CREATE SEQUENCE staff_seq START WITH 1;
CREATE SEQUENCE service_seq START WITH 1;
CREATE SEQUENCE order_seq START WITH 1;